'''Константы для модулей'''

COORD_MAX_X = 700
COORD_MAX_Y = 700
NUM_OF_CELLS_IN_A_ROW = 70
SIZE_OF_THE_CELL_X = int(COORD_MAX_X / NUM_OF_CELLS_IN_A_ROW)
SIZE_OF_THE_CELL_Y = int(COORD_MAX_Y / NUM_OF_CELLS_IN_A_ROW)